name: Build and publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} \
          | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker image
      run: |
        docker build -t plantuml:latest . \
          --build-arg "version=${GITHUB_REF##*/}"
    - name: Run test
      run: |
        docker run --rm -v $(pwd)/test:/data plantuml sequence.puml
        compare test/sequence.png test/expected-sequence.png -compose src test/sequence-diff.png
    - name: Upload test result
      uses: actions/upload-artifact@v2
      with:
        name: sequence-diff
        path: test/sequence-diff.png
    - name: Build version info
      run: |
        docker run --rm -v $(pwd)/test:/data plantuml version.puml
    - name: Upload verion info
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: test/version.png
    - name: Tag Docker image
      run: |
        docker tag plantuml:latest dstockhammer/plantuml:latest
        docker tag plantuml:latest dstockhammer/plantuml:${GITHUB_REF##*/}
    - name: Push Docker images
      run: |
        docker push dstockhammer/plantuml:${GITHUB_REF##*/}
        docker push dstockhammer/plantuml:latest
